// Builds the two Windows EXEs.
//
//   npm run exe
//
// Output (single self-contained files, no installer, no folder to copy):
//   release-win\SederPlus.exe        — the full app
//   release-win\SederPlusQuick.exe   — the quick-entry window
//
// Both are ~10MB, start instantly, and render through the WebView2 runtime
// that ships with Windows 11 (and is present on essentially all Windows 10
// installs). They share data through %APPDATA%\SederPlus\sedorim-data.json
// and can be open at the same time — see src-tauri/core/src/store.rs.
//
// Requires: Node (frontend) and a Rust toolchain (shell). The GitHub Actions
// workflow in .github/workflows/build-windows.yml runs exactly this.

import { execFileSync } from "node:child_process";
import { copyFileSync, existsSync, mkdirSync, rmSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const outDir = path.join(root, "release-win");
const buildInfoFile = path.join(root, "src", "lib", "build-info.ts");

const APPS = [
  { exe: "SederPlus.exe", crate: "full", label: "the full app" },
  { exe: "SederPlusQuick.exe", crate: "quick", label: "the quick-entry window" },
];

function run(command, args) {
  console.log(`\n> ${command} ${args.join(" ")}`);
  execFileSync(command, args, { cwd: root, stdio: "inherit", shell: process.platform === "win32" });
}

let stampedCommit = "unknown";

// Stamps the real git commit + build time into src/lib/build-info.ts *before*
// building, so the packaged app's About screen shows exactly what was built.
// This is a build artifact — restoreBuildInfo() puts the file back afterwards
// so running this never leaves a dirty working tree.
function stampBuildInfo() {
  try {
    stampedCommit = execFileSync("git", ["rev-parse", "--short", "HEAD"], { cwd: root })
      .toString()
      .trim();
  } catch {
    console.warn("⚠  Could not read the git commit — About will show 'unknown'.");
  }
  const buildTime = `${new Date().toISOString().replace("T", " ").slice(0, 16)} UTC`;
  writeFileSync(
    buildInfoFile,
    "// Generated by scripts/build-exes.mjs at build time — do not edit or commit changes here.\n" +
      `export const BUILD_COMMIT: string = ${JSON.stringify(stampedCommit)};\n` +
      `export const BUILD_TIME: string = ${JSON.stringify(buildTime)};\n`,
    "utf8"
  );
  console.log(`Build info stamped: commit ${stampedCommit}, ${buildTime}`);
}

function restoreBuildInfo() {
  writeFileSync(
    buildInfoFile,
    "// Fallback build-info for a plain `npm run dev` / `npm run build`. When\n" +
      "// building the EXEs, scripts/build-exes.mjs overwrites this file with the\n" +
      "// actual git commit SHA + build timestamp *before* the build, so the About\n" +
      "// screen always reflects exactly what was shipped — letting you check\n" +
      "// whether a given install has a given fix without guessing. It is\n" +
      "// regenerated on every `npm run exe`; don't rely on these values outside a\n" +
      "// packaged build.\n" +
      "//\n" +
      "// Typed as `string` (not an inferred literal) so comparisons like\n" +
      '// `BUILD_COMMIT !== "dev"` still typecheck after regeneration.\n' +
      'export const BUILD_COMMIT: string = "dev";\n' +
      'export const BUILD_TIME: string = "";\n',
    "utf8"
  );
}

function main() {
  rmSync(outDir, { recursive: true, force: true });
  mkdirSync(outDir, { recursive: true });

  try {
    stampBuildInfo();

    // One frontend build, embedded into both EXEs by tauri-build.
    run("npm", ["run", "build"]);

    for (const app of APPS) {
      console.log(`\n== ${app.exe} — ${app.label} ==`);
      // Plain cargo, no Tauri CLI. What makes that work is the
      // `custom-protocol` feature declared in each crate's Cargo.toml —
      // without it the EXE loads build.devUrl (localhost:5173) instead of the
      // frontend embedded in the binary. Don't remove it.
      run("cargo", [
        "build",
        "--release",
        "--manifest-path",
        path.join("src-tauri", app.crate, "Cargo.toml"),
      ]);

      // Workspace members share one target dir, so both land here.
      const built = path.join(root, "src-tauri", "target", "release", app.exe);
      if (!existsSync(built)) {
        throw new Error(
          `${app.exe} was not produced at ${built}. Check the cargo output above — ` +
            `the EXE name comes from the [[bin]] name in src-tauri/${app.crate}/Cargo.toml.`
        );
      }
      copyFileSync(built, path.join(outDir, app.exe));
      console.log(`✔ ${app.exe}`);
    }
  } finally {
    restoreBuildInfo();
  }

  console.log(
    `\n✔ Done — two single-file EXEs in ${outDir}:\n` +
      `    SederPlus.exe\n` +
      `    SederPlusQuick.exe\n\n` +
      `Copy either one anywhere and double-click it; there is nothing to install\n` +
      `and no folder of support files. They share %APPDATA%\\SederPlus\\sedorim-data.json,\n` +
      `so both can be open at once and see each other's entries within a few seconds.\n\n` +
      `Built from commit ${stampedCommit} — the app's "אודות" screen shows the same\n` +
      `value, so you can always tell which code an install actually has.`
  );
}

main();
