// Builds the app and packages it into two Windows EXEs designed to run
// AT THE SAME TIME, sharing the same local data and local server
// (see electron/main.cjs and electron/quick.cjs):
//   - SederPlus.exe  (full app)
//   - SederPlusQuick.exe    (quick entry window)
//
// Data (seder/learning/timer entries) lives in a shared JSON file written
// by the Nitro server — %APPDATA%\SederPlus\sedorim-data.json — NOT in
// Chromium's localStorage. Existing users upgrading from an older build
// (where data lived only in localStorage) get migrated automatically and
// silently the first time the new EXE runs: see
// migrateLegacyLocalStorageIfNeeded() in src/lib/kollel-store.ts. Nothing
// is deleted from localStorage during that migration — it's copied, not
// moved — so old data is never at risk even if the migration is interrupted.
//
// Usage (on Windows, in the project root):
//   npm install
//   npm run package:win
//
// Output lands in release-win\. A RunBoth.bat launcher is placed next to
// both app folders — double-click it to open both windows together.

import { execSync } from "node:child_process";
import { existsSync, rmSync, mkdirSync, cpSync, writeFileSync, renameSync, readdirSync, unlinkSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const outDir = path.join(root, "release-win");
const stagingDir = path.join(root, ".package-staging");

const pkg = JSON.parse(
  execSync("node -p \"JSON.stringify(require('./package.json'))\"", { cwd: root }).toString()
);

function run(cmd) {
  console.log(`\n> ${cmd}`);
  execSync(cmd, { cwd: root, stdio: "inherit" });
}

let stampedCommit = "unknown";

function writeBuildInfo() {
  // Stamps the real git commit + build time into src/lib/build-info.ts
  // *before* building, so the packaged app's About screen shows exactly
  // what was built — no more guessing whether a repackage actually picked
  // up the latest fixes. Overwrites the dev-build fallback in that file;
  // this is a build artifact, not meant to be committed.
  let commit = "unknown";
  try {
    commit = execSync("git rev-parse --short HEAD", { cwd: root }).toString().trim();
  } catch {
    console.warn("⚠  Could not determine git commit (not a git checkout?) — About screen will show 'unknown'.");
  }
  stampedCommit = commit;
  const buildTime = new Date().toISOString().replace("T", " ").slice(0, 16) + " UTC";
  const filePath = path.join(root, "src", "lib", "build-info.ts");
  writeFileSync(
    filePath,
    `// Generated by scripts/package-win.mjs at package time — do not edit or commit changes here.\n` +
      `export const BUILD_COMMIT: string = ${JSON.stringify(commit)};\n` +
      `export const BUILD_TIME: string = ${JSON.stringify(buildTime)};\n`,
    "utf8"
  );
  console.log(`Build info stamped: commit ${commit}, ${buildTime}`);
}

function restoreBuildInfoFallback() {
  // Puts src/lib/build-info.ts back exactly as it's committed in git, so
  // running this script never leaves your working tree dirty. Safe to call
  // even if writeBuildInfo() never ran or the build failed partway through.
  const filePath = path.join(root, "src", "lib", "build-info.ts");
  writeFileSync(
    filePath,
    `// Fallback build-info for the normal dev / Lovable-hosted build. When\n` +
      `// packaging the Windows EXEs, scripts/package-win.mjs overwrites this file\n` +
      `// with the actual git commit SHA + build timestamp *before* running the\n` +
      `// build, so About screen always reflects exactly what was packaged —\n` +
      `// letting you check whether a given install has fixed code without\n` +
      `// guessing. This file is regenerated on every `+"`npm run package:win`"+`; don't\n` +
      `// rely on its contents being meaningful outside a packaged build.\n` +
      `//\n` +
      `// Typed as `+"`string`"+` (not inferred literal) so comparisons like\n` +
      `// `+"`BUILD_COMMIT !== \"dev\"`"+` still typecheck correctly after this file is\n` +
      `// regenerated with a real commit hash.\n` +
      `export const BUILD_COMMIT: string = "dev";\n` +
      `export const BUILD_TIME: string = "";\n`,
    "utf8"
  );
}

function buildServer() {
  console.log("== Building server bundle (Nitro node-server preset) ==");
  run("npx vite build --config vite.electron.config.ts");

  // Nitro's node-server preset writes to .output/{server,public}. The
  // electron main processes (electron/main.cjs, electron/quick.cjs) look
  // for dist-node/server/index.mjs, so normalize the folder name here.
  const nitroOutput = path.join(root, ".output");
  const distNode = path.join(root, "dist-node");
  if (!existsSync(nitroOutput)) {
    throw new Error(".output not found after build — check the vite build logs above.");
  }
  rmSync(distNode, { recursive: true, force: true });
  renameSync(nitroOutput, distNode);
  console.log(`Server bundle ready at ${distNode}`);
}

function stageApp({ name, mainEntry }) {
  const appStagingDir = path.join(stagingDir, name);
  rmSync(appStagingDir, { recursive: true, force: true });
  mkdirSync(appStagingDir, { recursive: true });

  // Minimal package.json — no runtime npm deps are needed inside the
  // packaged app; Nitro already bundled everything into dist-node.
  writeFileSync(
    path.join(appStagingDir, "package.json"),
    JSON.stringify(
      {
        name: name.toLowerCase(),
        version: pkg.version || "1.0.0",
        private: true,
        main: `electron/${mainEntry}`,
      },
      null,
      2
    )
  );

  cpSync(path.join(root, "electron"), path.join(appStagingDir, "electron"), { recursive: true });
  cpSync(path.join(root, "dist-node"), path.join(appStagingDir, "dist-node"), { recursive: true });

  return appStagingDir;
}

// Electron ships translations for ~60 languages by default (Chromium's
// locales/*.pak). We only need Hebrew + English — deleting the rest saves
// several MB per app with zero effect on functionality.
const KEEP_LOCALES = new Set(["he.pak", "en-US.pak", "en.pak"]);

function pruneLocales(appOutDir) {
  const localesDir = path.join(appOutDir, "locales");
  if (!existsSync(localesDir)) return;
  let removed = 0;
  for (const file of readdirSync(localesDir)) {
    if (!KEEP_LOCALES.has(file)) {
      unlinkSync(path.join(localesDir, file));
      removed++;
    }
  }
  console.log(`Pruned ${removed} unused locale files from ${localesDir}`);
}

function packageApp({ name, appStagingDir, icon }) {
  console.log(`\n== Packaging ${name}.exe ==`);
  const iconArg = existsSync(icon) ? ` --icon="${icon}"` : "";
  run(
    `npx electron-packager "${appStagingDir}" "${name}" ` +
      `--platform=win32 --arch=x64 --out="${outDir}" --overwrite --asar` +
      iconArg
  );
  pruneLocales(path.join(outDir, `${name}-win32-x64`));
}

function writeRunBothLauncher() {
  // Launches both EXEs together. main.cjs / quick.cjs already handle the
  // race of both starting near-simultaneously (whichever binds the shared
  // port first "wins"; the other just attaches to it), so a plain
  // double-start here is safe.
  const bat = `@echo off
REM Launches SederPlus and SederPlusQuick together.
REM They share data (%APPDATA%\\SederPlus) and a local port automatically.
cd /d "%~dp0"
start "" "SederPlus-win32-x64\\SederPlus.exe"
timeout /t 1 /nobreak >nul
start "" "SederPlusQuick-win32-x64\\SederPlusQuick.exe"
`;
  writeFileSync(path.join(outDir, "RunBoth.bat"), bat, "utf8");
}

function main() {
  if (process.platform !== "win32") {
    console.warn(
      "\n⚠  You're not running this on Windows. electron-packager can still " +
        "produce a win32 build from another OS, but the Electron binary " +
        "download requires unrestricted internet access to " +
        "github.com/electron/electron release assets. If that download " +
        "fails, run this script on Windows instead.\n"
    );
  }

  try {
    writeBuildInfo();
    buildServer();

    rmSync(outDir, { recursive: true, force: true });
    rmSync(stagingDir, { recursive: true, force: true });

    const trackerIcon = path.join(root, "build", "tracker-icon.ico");
    const quickIcon = path.join(root, "build", "quick-icon.ico");

    const tracker = stageApp({ name: "SederPlus", mainEntry: "main.cjs" });
    packageApp({ name: "SederPlus", appStagingDir: tracker, icon: trackerIcon });

    const quick = stageApp({ name: "SederPlusQuick", mainEntry: "quick.cjs" });
    packageApp({ name: "SederPlusQuick", appStagingDir: quick, icon: quickIcon });

    writeRunBothLauncher();

    rmSync(stagingDir, { recursive: true, force: true });
  } finally {
    // Always put build-info.ts back to its committed state — even if the
    // build failed partway — so this script never leaves a dirty git
    // working tree behind.
    restoreBuildInfoFallback();
  }

  console.log(
    `\n✔ Done. Find everything under: ${outDir}\n` +
      `  SederPlus-win32-x64\\SederPlus.exe\n` +
      `  SederPlusQuick-win32-x64\\SederPlusQuick.exe\n` +
      `  RunBoth.bat   <- double-click this to launch both together\n\n` +
      `They share data via %APPDATA%\\SederPlus\\sedorim-data.json and a fixed ` +
      `local port (127.0.0.1:47821). Whichever opens first starts the shared ` +
      `local server; the second one just connects to it. Both can be open at ` +
      `the same time, on the same machine, safely.\n\n` +
      `Upgrading existing users: on first launch of this build, any data ` +
      `still sitting in the old localStorage (from a pre-1.0.2 install) is ` +
      `copied into sedorim-data.json automatically, once, with nothing ` +
      `deleted from localStorage. No manual migration step is needed.\n\n` +
      `Not sure if this build actually has the latest fixes? Open the app's ` +
      `"אודות" (About) screen — it shows "build ${stampedCommit}". Compare ` +
      `that against the latest commit SHA on GitHub (main branch) to confirm.`
  );
}

main();
